name: work on multiple jobs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: building

    steps:
      - name: printing..
        run: echo "building..."

  test:
    runs-on: ubuntu-latest
    name: testing
    needs: build

    steps:
      - name: printing
        run: echo "testing..."

  deploy:
    runs-on: ubuntu-latest
    name: deploying
    needs: test

    steps:
      - name: printing
        run: echo "deploying..."
      