name: learn varible concept in github actions

on:

  push:

    branches:
      - main

jobs:

  create:

    runs-on: ubuntu-latest

    env:
      AUTHOR: sandip

    steps:
      - run: echo "Application Name - ${{var.APP_NAME}}"
      - run: echo "Version - ${{var.VERSION}}"
      - run: echo "Author Name - $AUTHOR"
